#! /bin/bash

set -e
echo "This is the EZQuote system without the autocrop implementation"
read
./mat_code/test download 
read
./eztimate/code/Source eztimate/code/ez_logo.jpg images/cropped.jpg images/downloaded.jpg images/newest.jpg 
read
./mat_code/test upload
